
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: eks-demo
  name: app-eks-demo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-eks-demo
  replicas: 3 
  template: 
    metadata:
      labels:
        app: app-eks-demo
    spec:
      containers:
      - name: app-eks-demo
        image: CONTAINER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-eks-demo-service
  namespace: eks-demo
  labels:
    app: app-eks-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-eks-demo
  type: LoadBalancer